apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: DATABASE_URL
        - name: FEATURE_FLAG
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: FEATURE_FLAG
