apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # Base64 encoded value of 'password'
  api-key: YXBpa2V5  # Base64 encoded value of 'apikey'
